### ISSUE TITLE
permission issue while running the workshop

### ISSUE THREAD

**Issue by vvydier** [michaelhyatt/k8s-o11y-workshop#10]
@michaelhyatt When I followed the instructions on this workshop, I get the following issues. I checked to make sure my userid has permissions for .minikube and .kube directories, so there is something I am doing wrong, or the missing in the README
`Error loading config file "/etc/kubernetes/admin.conf": open /etc/kubernetes/admin.conf: permission denied`

**Comment by michaelhyatt** [comment]
Can you please provide me with more info on how to reproduce it? Versions of the OS, steps to run, etc?

**Comment by vvydier** [comment]
Latest version of ubuntu on AWS. A plain vanilla ubuntu on EC2 is what I used to test. Tried it on 2 instances from scratch and both came back with the same error

**Comment by michaelhyatt** [comment]
I tested it on Debian 9 and the instructions mention that. Can you please try it on Debian 9?

**Comment by michaelhyatt** [comment]
@vvydier let me know how you go with debian 9.
